name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master   # 分支名
    paths:
      - 'index.js'
      - 'wrangler.toml'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
